# Generated by Django 3.0.2 on 2020-01-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeSortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('domiciliation', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='possibility_test.Groupe')),
                ('typesortie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='possibility_test.TypeSortie')),
            ],
        ),
        migrations.CreateModel(
            name='ReseauxSociauxPersonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('personne', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='possibility_test.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='ReseauxSociauxGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('bandcamp', models.CharField(blank=True, max_length=100)),
                ('groupe', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='possibility_test.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('typeinstrument', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='possibility_test.Instrument')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='membre',
            field=models.ManyToManyField(blank=True, to='possibility_test.Personne'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='membre',
            field=models.ManyToManyField(blank=True, to='possibility_test.Personne'),
        ),
        migrations.CreateModel(
            name='ExemplaireInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeleinstrument', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='possibility_test.ModeleInstrument')),
                ('personne', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='possibility_test.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='CycleSortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etapesortie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='possibility_test.EtapeSortie')),
            ],
        ),
    ]
