# Generated by Django 3.0.2 on 2020-01-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('possibility_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='exemplaireinstrument',
            name='sensinstrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='possibility_test.SensInstrument'),
        ),
    ]
